spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://monorail.proxy.rlwy.net:22421/railway?createDatabaseIfNotExist=true
    username: root
    password: uZJMOOFPHQAhyoAmkszOmKEzOgwPGdzx

  jpa:
    hibernate:
      ddl-auto: update